test_app/singnle_app/urls.py
from django.urls import path
from .views import home, add_item,  delete_item, edit_item


app_name = "singnle_app"

urlpatterns = [
    path('', home, name='home'),
    path('add-item/', add_item, name='add-item'),
    path('edit-item/<int:pk>/', edit_item, name='edit-item'),
    path('delete-item/<int:pk>/', delete_item, name='delete-item'),
   
    
]

test_app/test_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('singnle_app.urls', namespace='singnle_app')),
    
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    

test_app/singnle_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Item(models.Model):
    title = models.CharField(max_length=100)
    price = models.FloatField() 
    description = models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    item_quantity = models.ForeignKey('ItemQuantity', on_delete=models.CASCADE,blank=True, null=True)
    date_created = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.title

    

class ItemQuantity(models.Model):   
    quantity = models.IntegerField(default=1, null=True)
    

test_app/singnle_app/forms.py
from django import forms

from .models import Item

class ItemForm(forms.ModelForm):

    class Meta:
        model = Item
        fields = ('title', 'price', 'description', 'item_quantity')

test_app/singnle_app/views.py
from django.shortcuts import render, redirect
from .models import Item, ItemQuantity
from django.contrib import messages
from .forms import ItemForm

# Create your views here.


def home(request):
    item_data = Item.objects.all().order_by("-date_created")
    
    context = {
        "item_data": item_data
    }
    return render(request, 'home.html', context )


def add_item(request):
     
    item = ''
    form = ItemForm()
    if request.method == "POST":
        form = ItemForm(request.POST)
        
        if form.is_valid():

            item_data = Item.objects.all()
            if item_data:
                # loop if item is found in db
                for item in item_data:       
                #check items cannot be added more than 10
                    if item.item_quantity.quantity <= 10:   
                        items = Item.objects.create(
                            title=form.cleaned_data["title"],
                            price=form.cleaned_data["price"],
                            description=form.cleaned_data["description"],
                            item_quantity=form.cleaned_data["item_quantity"],

                                )
                
                        items.save()
                        #increase qty by 1 for each item added
                        item.item_quantity.quantity += 1
                        item.item_quantity.save()
                        messages.success(request, 'Item added successfully')
                        return redirect("/")   
                    else:
                        messages.info(request, "You cannot add more than 10 items, delete some..")
                        return redirect("/")
            else:
                #if item is not in db, this will create item
                
                items = Item.objects.create(
                            title=form.cleaned_data["title"],
                            price=form.cleaned_data["price"],
                            description=form.cleaned_data["description"],
                            item_quantity=form.cleaned_data["item_quantity"],

                                )
                #programmatic create the quantity object
                item_qty=ItemQuantity.objects.create(quantity=1)
                item_qty.save()
                
                items.save()
                messages.success(request, "Item added successfully")
                return redirect("/")
    return render(request, 'add_item.html', {"form":form})
    
    
def edit_item(request, pk):
    item_data = Item.objects.get(id=pk)
    form = EditItemForm(instance=item_data)
    if request.method == "POST":
        #pre-field form data of single item to be updated
        form = ItemForm(request.POST, instance=item_data)
        if form.is_valid():
    
            form.save()
            messages.success(request, 'Item updated successfully')
            return redirect("/")
          
    context={
        'form':form,
        "item-data": item_data
    }
    return render(request, 'edit_item.html', context)
            
def delete_item(request, pk):
    
        #query database for the item
    item_data = Item.objects.get(id=pk)
         
    item_data.delete() 
    #decrease qty by 1 for each item deleted  
    item_data.item_quantity.quantity -= 1
    item_data.item_quantity.save()    
            
    messages.success(request, 'Item deleted')
    return redirect("/")
            
            
    

test_app/templates/add_item.html
{% extends "base.html" %}

{% block content %}
{% load crispy_forms_tags %}
 
   
  <!--Main layout-->
  <main>
    <div class="container">

        <form method="POST" action="{% url 'singnle_app:add-item' %}" >
            {% csrf_token %}
            {{ form|crispy }}
            
            
            <button class="btn btn-primary" type="submit">Add Item</button>
          </form> 
     
    </div>
  </main>
  <!--Main layout-->

  

  {% endblock content %}

test_app/templates/base.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Material Design Bootstrap -->
    <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
    <!-- Your custom styles (optional) -->
    <link href="{% static 'css/style.min.css' %}" rel="stylesheet">
    <link href="{% static 'sq-payment-form.css' %}" rel="stylesheet">
  
  
</head>

  
<body>

 <!-- Navbar -->
 <nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
  <div class="container">

    <!-- Brand -->
    <a class="nav-link waves-effect" href="">
      <strong class="blue-text">KimTech Assessment Test</strong>
    </a>

    

    <!-- Links -->
    <div class="collapse navbar-collapse" id="navbarSupportedContent">

      <!-- Left -->
      <ul class="navbar-nav mr-auto">
       
       
      </ul>

     
       
        </li>
      </ul>

    </div>

  </div>
</nav>
<!-- Navbar -->

  <div class="mt-5 pt-4">
  {% if messages %}
    {% for message in messages %}
    </div>
    <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
      {{ message }} 
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endfor %}
{% endif %}
</div>

  
    {% block content  %}
    {% endblock content %}
    
     <!-- SCRIPTS -->
  <!-- JQuery -->
  <script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
  <!-- Bootstrap tooltips -->
  <script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
  <!-- Bootstrap core JavaScript -->
  <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
  <!-- MDB core JavaScript -->
  <script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'sq-payment-form.js' %}"></script>
  <!-- Initializations -->
  <script type="text/javascript">
    // Animations initialization
    new WOW().init();

  </script>
  <footer class="page-footer text-center font-small mt-4 wow fadeIn">

   
    <hr class="my-4">

    <!-- Social icons -->
    <div class="pb-4">
      <a href="https://web.facebook.com/kimbitrus.choji.7" target="_blank">
        <i class="fab fa-facebook-f mr-3"></i>
      </a>

      <a href="https://twitter.com/bitrus_kim" target="_blank">
        <i class="fab fa-twitter mr-3"></i>
      </a>

      
      <a href="https://github.com/KimBitrus26" target="_blank">
        <i class="fab fa-github mr-3"></i>
      </a>

      
    </div>
    <!-- Social icons -->

    <!--Copyright-->
    <div class="footer-copyright py-3">
      © 2021 Copyright:
      <h2>KimTech</h2>
    </div>
    <!--/.Copyright-->

  </footer>
  
</body>
</html>

test_app/templates/edit_item.html
{% extends "base.html" %}

{% block content %}
{% load crispy_forms_tags %}
 
   
  <!--Main layout-->
  <main>
    <div class="container">

        <form method="POST" action="" >
            {% csrf_token %}
            {{ form|crispy }}
            
            
            <button class="btn btn-primary" type="submit">Edit Item</button>
          </form> 
     
    </div>
  </main>
  <!--Main layout-->

  

  {% endblock content %}

test_app/templates/home.html
{% extends "base.html" %}

{% block content %}
 
   
  <!--Main layout-->
  <main>
    <div class="container">

        <div class="table-responsive">
            <h2>Items</h2>
             
        
            <table class="table">
              <thead>
                <tr>
                    <th scope="col">S/N</th>
                  <th scope="col">Item title</th>
                  <th scope="col">Price</th>
                  <th scope="col">description</th>
                  <th scope="col">Created date</th>
                   <th scope="col"></th> 
                   <th scope="col"></th> 
                 
                 
                </tr>
              </thead>

              
              
              <tbody>
                {% for item in item_data %} 
                
                <tr>
                  <th scope="row">{{forloop.counter}}</th>
                  <td>{{ item.title }}</td>
                  <td>{{ item.price }}</td>
                  <td> {{ item.description }} </td>
                    <td> {{ item.date_created }} </td>   
                    <td> 
                      <a class="btn btn-primary float-right" href="{% url 'singnle_app:edit-item' item.id %}">Edit item</a>
                  </td> 
                    <td> 
                      <a href="{% url 'singnle_app:delete-item' item.id %}">
                        <i style="color: red;"class="fas fa-trash float-right"></i>
                          </a>
                    </td>            
                  
                </tr>
                
                     
            {% endfor %}
              </tbody>
              
               <tr>
                <td colspan="7">
                    <a class="btn btn-primary float-right" href="{% url 'singnle_app:add-item' %} ">Add item</a>
                </td>
            </tr>
              
            </table>
          </div>
      
     
    </div>
  </main>
  <!--Main layout-->

  

  {% endblock content %}